### ISSUE TITLE
Camera does not initialyse with python 3.7.5

### ISSUE THREAD

**Issue by KejaPower** [thehapyone/NanoCamera#11]
Hello,

I m able to initialize the camera when using python 3.6 but it's not working with python 3.7

The error code I get from camera.hasError(), is :

1 = Error: Could not initialize camera.

```
>>> import nanocamera as nano
>>> camera=nano.Camera(debug=True)
Traceback (most recent call last):
  File "/home/seller/.local/lib/python3.7/site-packages/nanocamera/NanoCam.py", line 163, in __open_csi
    raise RuntimeError()
RuntimeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/seller/.local/lib/python3.7/site-packages/nanocamera/NanoCam.py", line 47, in __init__
    self.open()
  File "/home/seller/.local/lib/python3.7/site-packages/nanocamera/NanoCam.py", line 122, in open
    self.__open_csi()
  File "/home/seller/.local/lib/python3.7/site-packages/nanocamera/NanoCam.py", line 168, in __open_csi
    raise RuntimeError('Error: Could not initialize CSI camera.')
RuntimeError: Error: Could not initialize CSI camera.


```

**Comment by wetzlarb** [comment]
Having the same issue.. Did you find a solution?

**Comment by neuralcoral** [comment]
Commenting that I had the same issue on `3.10` . I switch to 3.6, and that worked.
