### ISSUE TITLE
CSI Camera Never Ready

### ISSUE THREAD

**Issue by tomvdb** [thehapyone/NanoCamera#8]
**Describe the bug**
CSI Camera never ready. Tested with the python example and always shows CSI Camera Ready? - False

**To Reproduce**

```
import cv2
#from nanocamera.NanoCam import Camera
import nanocamera as nano

if __name__ == '__main__':
    # Create the Camera instance
    camera = nano.Camera(flip=0, width=1280, height=800, fps=30)
    print('CSI Camera ready? - ', camera.isReady())
    while camera.isReady():
        try:
            # read the camera image
            frame = camera.read()
            # display the frame
            cv2.imshow("Video Frame", frame)
            if cv2.waitKey(25) & 0xFF == ord('q'):
                break
        except KeyboardInterrupt:
            break

    # close the camera instance
    camera.release()

    # remove camera object
    del camera

```

**Desktop (please complete the following information):**
Standard Jetson Nano SDK - Jetpack 4.4

**Additional context**
CSI Camera works fine using the nvgstcapture-1.0 command

**Comment by tomvdb** [comment]
Additional info, enabling debug only provides this:

```
Traceback (most recent call last):
  File "/home/rover/.local/lib/python3.6/site-packages/nanocamera/NanoCam.py", line 163, in __open_csi
    raise RuntimeError()
RuntimeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nanocameratest.py", line 7, in <module>
    camera = nano.Camera( flip=0, width=640, height=480, fps=30, debug=True)
  File "/home/rover/.local/lib/python3.6/site-packages/nanocamera/NanoCam.py", line 47, in __init__
    self.open()
  File "/home/rover/.local/lib/python3.6/site-packages/nanocamera/NanoCam.py", line 122, in open
    self.__open_csi()
  File "/home/rover/.local/lib/python3.6/site-packages/nanocamera/NanoCam.py", line 168, in __open_csi
    raise RuntimeError('Error: Could not initialize CSI camera.')
RuntimeError: Error: Could not initialize CSI camera.

```

Also getting same results with usb camera, except that the could not initialize message changes to USB camera

**Comment by tomvdb** [comment]
Looks like the problem might be that my opencv-python is not built with gstreamer support, will confirm

**Comment by tomvdb** [comment]
Problem resolved, opencv was not built with gstreamer support. The installed versions on a clean image is good, but if you install opencv from apt then it installs a version without gstreamer support. all good now :)
